### ISSUE TITLE
[BUG] Ferryman seemingly breaks from the mod

### ISSUE THREAD

**Issue by UntotenTheo** [RealKC/UltraFumos#6]
i have no clue either

Console Logs:
![image](https://github.com/RealKC/UltraFumos/assets/75056493/c82dbd9e-909f-464e-9d1a-9c972a1d6542)

**Comment by UntotenTheo** [comment]
Uncertain about which version I was on, but I'll try updating, one moment

**Comment by UntotenTheo** [comment]
That worked, thank you!

**Comment by RealKC** [comment]
> Uncertain about which version I was on

Yeah I should really make the mod print its version in the logs...
